/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_goost_jcmatweann_NeuralNet */

#ifndef _Included_de_goost_jcmatweann_NeuralNet
#define _Included_de_goost_jcmatweann_NeuralNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_goost_jcmatweann_NeuralNet
 * Method:    activate
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_goost_jcmatweann_NeuralNet_activate
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
