/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_goost_jcmatweann_CMATWEANN_GetPointerFailedException */

#ifndef _Included_de_goost_jcmatweann_CMATWEANN_GetPointerFailedException
#define _Included_de_goost_jcmatweann_CMATWEANN_GetPointerFailedException
#ifdef __cplusplus
extern "C" {
#endif
#undef de_goost_jcmatweann_CMATWEANN_GetPointerFailedException_serialVersionUID
#define de_goost_jcmatweann_CMATWEANN_GetPointerFailedException_serialVersionUID -3042686055658047285LL
#undef de_goost_jcmatweann_CMATWEANN_GetPointerFailedException_serialVersionUID
#define de_goost_jcmatweann_CMATWEANN_GetPointerFailedException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
